config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  get    '/student_registration',  to: 'students#new'
  get    '/student_performance',  to: 'student_performances#performance_graph'

  resources :students
  resources :student_performances

  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  namespace :api do
    namespace :v1 do
      resource :student_performances
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sample.rb
class Sample
  def self.create_users
    5.times.each do |i|
      User.create(username: "user_#{i+1}", password: 'password')
    end
  end

  def self.create_schools
    3.times.each do |i|
      School.create(school_code: "school_#{i+1}", school_name: "School #{i+1}")
    end
  end

  def self.create_students
    index = 1
    School.all.each do |school|
      4.times.each do |i|
        Student.create(student_id: "stu_#{index}", name: "Student #{index}", sex: 'F', school_id: school.id)
        index = index + 1
      end
    end
  end

  def self.create_student_performances
    School.all.each do |school|
      school.students.each do |student|
        StudentPerformance::SEMESTER.each do |semester|
          StudentPerformance::SUBJECT.each do |subject|
            StudentPerformance.create(student_id: student.id, grade: 4, school_year: "2018-2019", subject: subject, semester: semester, score: rand(0..10))
          end
        end
      end
    end
  end

end

app/models/school.rb
class School < ApplicationRecord
  has_many :students
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :school
  validates :student_id, :presence => true
  validates :name, :presence => true
  validates :sex, :presence => true

  paginates_per 50

end

app/models/student_performance.rb
class StudentPerformance < ApplicationRecord
  belongs_to :student
  validates_inclusion_of :score, :in => 1..10


  SEMESTER = [1,2]
  GRADE = [1,2,3,4,5,6]
  SCHOOL_YEAR = ["2018-2019", "2019-2020"]
  SUBJECT = ["Mathematics", "Khmer Literature", "Social Study"]

  def self.by(student_id, year, semester, subject)
    self.find_by(student_id: student_id, school_year: year, semester: semester, subject: subject)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/api/v1/student_performances_controller.rb
module Api::V1
  class StudentPerformancesController < ApplicationController
    def show
      result = StudentPerformance.where(school_year: params[:school_year], student_id: params[:student_id])
      render json: {result: result}
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_url
    else
      flash.now[:danger] = 'Invalid username/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/student_performances_controller.rb
class StudentPerformancesController < ApplicationController
  def index
    performances = apply_filter(params)
    @student_performances = performances.select(:student_id, :school_year, :grade).distinct
  end

  def new
    @student_performance = StudentPerformance.new
  end

  def create
    student_performance = StudentPerformance.create(student_performance_params)

    redirect_to root_path
  end

  def show

  end

  def performance_graph
    @students = Student.where(school_id: params[:school_id]) || []
    if params[:student_id] && params[:student_id] != ""
      @student = Student.find(params[:student_id])
      @total_score = StudentPerformance.where(student_id: params[:student_id], school_year: params[:school_year]).sum(:score)
      @status = ((@total_score*100)/60 > 60) ?  "Pass" : "Fail"
    end
    @performances = apply_filter(params)
  end

  private
  def student_performance_params
    # params.require(:student_performance).permit(:school_year, :student_id, :grade)
  end

  def apply_filter(params)
    performances = StudentPerformance.all

    if(params[:school_id] && params[:school_id] != "")
      performances = StudentPerformance.joins(:student).where("students.school_id = #{params[:school_id]}")
    end

    if(params[:school_year] && params[:school_year] != "")
      performances = performances.where(school_year: params[:school_year])
    end

    if(params[:grade] && params[:grade] != "")
      performances = performances.where(grade: params[:grade])
    end

    if(params[:student_id] && params[:student_id] != "")
      performances = performances.where(student_id: params[:student_id])
    end

    return performances
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.page params[:page]
  end

  def new
    @student = Student.new
  end

  def create
    student = Student.new(student_params)
    if(student.save)
      redirect_to students_path
    else
      flash[:danger] = 'Please enter all the required field'
      render :new
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      flash[:notice] = 'Student updated!'
      redirect_to students_path(@student)
    else
      flash[:error] = 'Failed to edit student!'
      render :edit
    end
  end

  def show
    @student = Student.find(params[:id])
  end

  def destroy
    @student = Student.find(params[:id])
    if @student.delete
      flash[:notice] = 'Student deleted!'
      redirect_to students_path
    else
      flash[:error] = 'Failed to delete this student!'
      render :destroy
    end
  end

  private
  def student_params
    params.require(:student).permit(:student_id, :name, :sex, :date_of_birth, :school_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  def log_out
    session.delete(:user_id)
  end
end

app/helpers/student_performances_helper.rb
module StudentPerformancesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="#">My Project</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Student', students_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Report', student_performances_path, class: 'nav-link' %>
        </li>

        <li class="nav-item">
          <%= link_to 'Performance', student_performance_path, class: 'nav-link' %>
        </li>
      </ul>
      <div class="float-right">
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <% if current_user %>
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                <%= current_user.username %>
              </a>
            <% else %>
              <%= link_to "Login", login_path, :class => 'nav-link'  %>
            <% end %>
            <div class="dropdown-menu">
              <%= link_to "Log out", logout_path, method: :delete, class: 'dropdown-item' %>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myproj</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <br/>
    <div class="container">
      <%= render 'share/alert' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/share/_alert.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
  <%= alert %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  </div>
<% end %>

app/views/student_performances/index.html.erb
<h5>Student Performance</h5>
<div class="form-search">
  <%= form_tag(student_performances_path, method: :get) do %>
    <div class="form-row align-items-center">
      <div class="col-auto">
        <label class="sr-only" for="inlineFormInput">School Name</label>
        <%= select_tag(:school_id, options_from_collection_for_select(School.all, 'id', 'school_name', params[:school_id]), include_blank: 'School Name', class: 'form-control') %>
      </div>

      <div class="col-auto">
        <label class="sr-only" for="inlineFormInput">School Year</label>
        <%= select_tag(:school_year, options_for_select(StudentPerformance::SCHOOL_YEAR, params[:school_year]),include_blank: 'School Year', class: 'form-control') %>
      </div>

      <div class="col-auto">
        <label class="sr-only" for="inlineFormInput">Grade</label>
        <%= select_tag(:grade, options_for_select(StudentPerformance::GRADE, params[:grade]), include_blank: 'Grade', class: 'form-control') %>
      </div>
      <%= submit_tag 'Search', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">School Name</th>
      <th scope="col">School Year</th>
      <th scope="col">Student Name</th>
      <th scope="col">Grade</th>

      <% StudentPerformance::SEMESTER.each do |semester| %>
        <th colspan="3" style="text-align: center">
          <span>Semester <%= semester %></span>
          <table>
            <tr>
              <% StudentPerformance::SUBJECT.each do |subject| %>
                <td><%= subject %></td>
              <% end %>
            </tr>
          </table>
        </th>
      <% end %>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>

    <% @student_performances.each do |sp| %>
      <tr>
        <td><%= sp.student.student_id %></td>
        <td><%= sp.student.school.school_name %></td>
        <td><%= sp.school_year %></td>
        <td><%= sp.student.name %></td>
        <td><%= sp.grade %></td>
        <% StudentPerformance::SEMESTER.each do |semester| %>
          <% StudentPerformance::SUBJECT.each do |subject| %>
            <td><%= StudentPerformance.by(sp.student_id, sp.school_year, semester, subject).try(:score) %></td>
          <% end %>
        <% end %>
        <td>
          Edit |
          Delete
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="float-right">
  <%#= paginate @students %>
</div>

app/views/student_performances/new.html.erb
<div class="container">
  <h1>Student Study Performance</h1>
  <div class="row">
    <%= form_for(@student_performance, url: student_performances_path) do |f| %>
       <%= f.fields_for :semester do |s| %>
         <%= s.text_field :score %>
       <% end %>
    <% end %>
  </div>
</div>

app/views/student_performances/performance_graph.html.erb
<h5>Student Study Performance</h5>
<%= form_tag(student_performance_path, method: :get) do %>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">School Year</label>
    <div class="col-sm-4">
      <%= select_tag(:school_year, options_for_select(StudentPerformance::SCHOOL_YEAR, params[:school_year]), class: 'form-control', onchange: 'this.form.submit();') %>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-2 col-form-label">School Name</label>
    <div class="col-sm-4">
      <%= select_tag(:school_id, options_from_collection_for_select(School.all, 'id', 'school_name', params[:school_id]), include_blank: 'Select School', class: 'form-control', onchange: 'this.form.submit();') %>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Student Name</label>
    <div class="col-sm-4">
      <%= select_tag(:student_id, options_from_collection_for_select(@students, 'id', 'name', params[:student_id]), include_blank: 'Select Student', class: 'form-control', onchange: 'this.form.submit();') %>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Student Id</label>
    <div class="col-sm-4">
      <label><%= @student.try(:student_id) %></label>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Grade</label>
    <div class="col-sm-4">
      <label><%#= @student.grade %></label>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Sex</label>
    <div class="col-sm-4">
      <label><%= @student.try(:sex) %></label>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Date of Birth</label>
    <div class="col-sm-4">
      <label><%= @student.try(:date_of_birth) %></label>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-3 col-form-label">Total score of both semester is</label>
    <div class="col-sm-4">
      <label><%= @total_score %></label>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Study Result</label>
    <div class="col-sm-4">
      <label class="text-primary"><%= @status %></label>
    </div>
  </div>
  <% if @student %>
    <%= column_chart @performances.group(:subject,:semester).sum(:score), min: 0, max: 10 %>
  <% end %>

<% end %>

app/views/student_performances/show.html.erb
Show

app/views/students/edit.html.erb
<h5>Edit Student</h5>
<%= form_for @student, :url => {:controller => :students, action: :update} do |f| %>
  <div class="form-group row">
    <%= f.label 'Student ID *', class: "col-sm-2 col-form-label" %>
    <div class="col-sm-7">
      <%= f.text_field :student_id, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label 'Name * ', class: "col-sm-2 col-form-label" %>
    <div class="col-sm-7">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label 'Gender', class: "col-sm-2 col-form-label" %>
    <div class="col-sm-7">
      <%= f.collection_select(:sex, { 'F' => 'Female', 'M' => 'Male' }, :first, :last, {}, class: 'form-control') %>
    </div>
  </div>
  <br/>
  <div class="form-group row">
    <%= f.label 'Date of birth', class: "col-sm-2 col-form-label" %>
    <div class="col-sm-7">
      <%= f.date_field :date_of_birth, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label 'School Name', class: "col-sm-2 col-form-label" %>
    <div class="col-sm-7">
      <%= f.select(:school_id, options_from_collection_for_select(School.all, 'id', 'school_name'),{}, class: 'form-control') %>
    </div>
  </div>

  <div class="form-group row justify-content-end">
    <div class="col-sm-8">
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
    </div>

  </div>
<% end %>

app/views/students/index.html.erb
<h5>List of students</h5>
<div class="float-right">
  <%= link_to 'Student Registration', new_student_path, class: 'btn btn-primary' %>
</div>
<br/>
<br/>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Sex</th>
      <th scope="col">Date of Birth</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <th scope="row"><%= student.student_id %></th>
        <td><%= student.name %></td>
        <td><%= student.sex %></td>
        <td><%= student.date_of_birth %></td>
        <td>
          <%= link_to 'Edit', edit_student_path(student) %> |
          <%= link_to 'Delete', student_path(student), method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="float-right">
  <%= paginate @students %>
</div>

app/views/students/new.html.erb
<h5>Student Registration</h5>
<%= form_for(:student, url: students_path) do |f| %>
  <div class="form-group row">
    <%= f.label 'Student ID *', class: "col-sm-2 col-form-label" %>
    <div class="col-sm-7">
      <%= f.text_field :student_id, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label 'Name * ', class: "col-sm-2 col-form-label" %>
    <div class="col-sm-7">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label 'Gender', class: "col-sm-2 col-form-label" %>
    <div class="col-sm-7">
      <%= f.collection_select(:sex, { 'F' => 'Female', 'M' => 'Male' }, :first, :last, {}, class: 'form-control') %>
    </div>
  </div>
  <br/>
  <div class="form-group row">
    <%= f.label 'Date of birth', class: "col-sm-2 col-form-label" %>
    <div class="col-sm-7">
      <%= f.date_field :date_of_birth, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label 'School Name', class: "col-sm-2 col-form-label" %>
    <div class="col-sm-7">
      <%= f.select(:school_id, options_from_collection_for_select(School.all, 'id', 'school_name'),{}, class: 'form-control') %>
    </div>
  </div>

  <div class="form-group row justify-content-end">
    <div class="col-sm-8">
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
    </div>

  </div>
<% end %>

app/views/students/show.html.erb
Successfully save student